FROM node:16-alpine

ARG NX_GITHUB_SECRET
ARG NX_GITHUB_CLIENT_ID
ARG NX_GITHUB_REDIRECT_URI

COPY . /usr/src/app

WORKDIR /usr/src/app

ENV NX_GITHUB_SECRET=$NX_GITHUB_SECRET
ENV NX_GITHUB_CLIENT_ID=$NX_GITHUB_CLIENT_ID
ENV NX_GITHUB_REDIRECT_URI=$NX_GITHUB_REDIRECT_URI

RUN npm install
RUN npm run build


ENTRYPOINT ["node", "./dist/apps/api/main.js"]